// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/moderation.proto

package moderationv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModerationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModerationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModerationRequestMultiError, or nil if none found.
func (m *CreateModerationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModerationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProductId

	// no validation rules for AdminId

	// no validation rules for Active

	if len(errors) > 0 {
		return CreateModerationRequestMultiError(errors)
	}

	return nil
}

// CreateModerationRequestMultiError is an error wrapping multiple validation
// errors returned by CreateModerationRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateModerationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModerationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModerationRequestMultiError) AllErrors() []error { return m }

// CreateModerationRequestValidationError is the validation error returned by
// CreateModerationRequest.Validate if the designated constraints aren't met.
type CreateModerationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModerationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModerationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModerationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModerationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModerationRequestValidationError) ErrorName() string {
	return "CreateModerationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModerationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModerationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModerationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModerationRequestValidationError{}

// Validate checks the field values on CreateModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateModerationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateModerationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateModerationResponseMultiError, or nil if none found.
func (m *CreateModerationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateModerationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetModeration()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModeration()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateModerationResponseValidationError{
				field:  "Moderation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateModerationResponseMultiError(errors)
	}

	return nil
}

// CreateModerationResponseMultiError is an error wrapping multiple validation
// errors returned by CreateModerationResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateModerationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateModerationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateModerationResponseMultiError) AllErrors() []error { return m }

// CreateModerationResponseValidationError is the validation error returned by
// CreateModerationResponse.Validate if the designated constraints aren't met.
type CreateModerationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateModerationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateModerationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateModerationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateModerationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateModerationResponseValidationError) ErrorName() string {
	return "CreateModerationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateModerationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateModerationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateModerationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateModerationResponseValidationError{}

// Validate checks the field values on GetModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModerationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModerationRequestMultiError, or nil if none found.
func (m *GetModerationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModerationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ModerationId

	if len(errors) > 0 {
		return GetModerationRequestMultiError(errors)
	}

	return nil
}

// GetModerationRequestMultiError is an error wrapping multiple validation
// errors returned by GetModerationRequest.ValidateAll() if the designated
// constraints aren't met.
type GetModerationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModerationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModerationRequestMultiError) AllErrors() []error { return m }

// GetModerationRequestValidationError is the validation error returned by
// GetModerationRequest.Validate if the designated constraints aren't met.
type GetModerationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModerationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModerationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModerationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModerationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModerationRequestValidationError) ErrorName() string {
	return "GetModerationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModerationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModerationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModerationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModerationRequestValidationError{}

// Validate checks the field values on GetModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModerationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModerationResponseMultiError, or nil if none found.
func (m *GetModerationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModerationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetModeration()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModeration()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetModerationResponseValidationError{
				field:  "Moderation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetModerationResponseMultiError(errors)
	}

	return nil
}

// GetModerationResponseMultiError is an error wrapping multiple validation
// errors returned by GetModerationResponse.ValidateAll() if the designated
// constraints aren't met.
type GetModerationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModerationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModerationResponseMultiError) AllErrors() []error { return m }

// GetModerationResponseValidationError is the validation error returned by
// GetModerationResponse.Validate if the designated constraints aren't met.
type GetModerationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModerationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModerationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModerationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModerationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModerationResponseValidationError) ErrorName() string {
	return "GetModerationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModerationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModerationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModerationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModerationResponseValidationError{}

// Validate checks the field values on UpdateModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateModerationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateModerationRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateModerationRequestMultiError, or nil if none found.
func (m *UpdateModerationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateModerationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Active

	if m.AdminId != nil {
		// no validation rules for AdminId
	}

	if len(errors) > 0 {
		return UpdateModerationRequestMultiError(errors)
	}

	return nil
}

// UpdateModerationRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateModerationRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateModerationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateModerationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateModerationRequestMultiError) AllErrors() []error { return m }

// UpdateModerationRequestValidationError is the validation error returned by
// UpdateModerationRequest.Validate if the designated constraints aren't met.
type UpdateModerationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateModerationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateModerationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateModerationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateModerationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateModerationRequestValidationError) ErrorName() string {
	return "UpdateModerationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateModerationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateModerationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateModerationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateModerationRequestValidationError{}

// Validate checks the field values on UpdateModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateModerationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateModerationResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateModerationResponseMultiError, or nil if none found.
func (m *UpdateModerationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateModerationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetModeration()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateModerationResponseValidationError{
					field:  "Moderation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetModeration()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateModerationResponseValidationError{
				field:  "Moderation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateModerationResponseMultiError(errors)
	}

	return nil
}

// UpdateModerationResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateModerationResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateModerationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateModerationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateModerationResponseMultiError) AllErrors() []error { return m }

// UpdateModerationResponseValidationError is the validation error returned by
// UpdateModerationResponse.Validate if the designated constraints aren't met.
type UpdateModerationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateModerationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateModerationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateModerationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateModerationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateModerationResponseValidationError) ErrorName() string {
	return "UpdateModerationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateModerationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateModerationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateModerationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateModerationResponseValidationError{}

// Validate checks the field values on ListModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModerationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModerationRequestMultiError, or nil if none found.
func (m *ListModerationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModerationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AdminId

	// no validation rules for Limit

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListModerationRequestMultiError(errors)
	}

	return nil
}

// ListModerationRequestMultiError is an error wrapping multiple validation
// errors returned by ListModerationRequest.ValidateAll() if the designated
// constraints aren't met.
type ListModerationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModerationRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModerationRequestMultiError) AllErrors() []error { return m }

// ListModerationRequestValidationError is the validation error returned by
// ListModerationRequest.Validate if the designated constraints aren't met.
type ListModerationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModerationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModerationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModerationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModerationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModerationRequestValidationError) ErrorName() string {
	return "ListModerationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListModerationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModerationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModerationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModerationRequestValidationError{}

// Validate checks the field values on ListModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListModerationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListModerationResponseMultiError, or nil if none found.
func (m *ListModerationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListModerationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetModeration() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListModerationResponseValidationError{
						field:  fmt.Sprintf("Moderation[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListModerationResponseValidationError{
						field:  fmt.Sprintf("Moderation[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListModerationResponseValidationError{
					field:  fmt.Sprintf("Moderation[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListModerationResponseMultiError(errors)
	}

	return nil
}

// ListModerationResponseMultiError is an error wrapping multiple validation
// errors returned by ListModerationResponse.ValidateAll() if the designated
// constraints aren't met.
type ListModerationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListModerationResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListModerationResponseMultiError) AllErrors() []error { return m }

// ListModerationResponseValidationError is the validation error returned by
// ListModerationResponse.Validate if the designated constraints aren't met.
type ListModerationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListModerationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListModerationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListModerationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListModerationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListModerationResponseValidationError) ErrorName() string {
	return "ListModerationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListModerationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListModerationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListModerationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListModerationResponseValidationError{}

// Validate checks the field values on Moderation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Moderation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Moderation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ModerationMultiError, or
// nil if none found.
func (m *Moderation) ValidateAll() error {
	return m.validate(true)
}

func (m *Moderation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AdminId

	// no validation rules for ProductId

	// no validation rules for Active

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModerationMultiError(errors)
	}

	return nil
}

// ModerationMultiError is an error wrapping multiple validation errors
// returned by Moderation.ValidateAll() if the designated constraints aren't met.
type ModerationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationMultiError) AllErrors() []error { return m }

// ModerationValidationError is the validation error returned by
// Moderation.Validate if the designated constraints aren't met.
type ModerationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationValidationError) ErrorName() string { return "ModerationValidationError" }

// Error satisfies the builtin error interface
func (e ModerationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModeration.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationValidationError{}
