// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: moderation/v1/moderation.proto

package moderationv1

import (
	v1 "github.com/nhassl3/servicehub-contracts/pkg/pb/product/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPending  int32                  `protobuf:"varint,1,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`
	TotalApproved int32                  `protobuf:"varint,2,opt,name=total_approved,json=totalApproved,proto3" json:"total_approved,omitempty"`
	TotalRejected int32                  `protobuf:"varint,3,opt,name=total_rejected,json=totalRejected,proto3" json:"total_rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetTotalPending() int32 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *StatsResponse) GetTotalApproved() int32 {
	if x != nil {
		return x.TotalApproved
	}
	return 0
}

func (x *StatsResponse) GetTotalRejected() int32 {
	if x != nil {
		return x.TotalRejected
	}
	return 0
}

type RejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{2}
}

func (x *RejectRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *RejectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *v1.Product            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectResponse) Reset() {
	*x = RejectResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResponse) ProtoMessage() {}

func (x *RejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResponse.ProtoReflect.Descriptor instead.
func (*RejectResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{3}
}

func (x *RejectResponse) GetProduct() *v1.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ApproveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *v1.Product            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveResponse) GetProduct() *v1.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{7}
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *Moderation            `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResponse) Reset() {
	*x = ClaimResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResponse) ProtoMessage() {}

func (x *ClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResponse.ProtoReflect.Descriptor instead.
func (*ClaimResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimResponse) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{10}
}

func (x *QueueRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueueRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type QueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*QueueProduct        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResponse) Reset() {
	*x = QueueResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResponse) ProtoMessage() {}

func (x *QueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResponse.ProtoReflect.Descriptor instead.
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{11}
}

func (x *QueueResponse) GetProducts() []*QueueProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *QueueResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModerationRequest) Reset() {
	*x = CreateModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModerationRequest) ProtoMessage() {}

func (x *CreateModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModerationRequest.ProtoReflect.Descriptor instead.
func (*CreateModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{12}
}

func (x *CreateModerationRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateModerationRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *CreateModerationRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *Moderation            `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateModerationResponse) Reset() {
	*x = CreateModerationResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModerationResponse) ProtoMessage() {}

func (x *CreateModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModerationResponse.ProtoReflect.Descriptor instead.
func (*CreateModerationResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{13}
}

func (x *CreateModerationResponse) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type GetModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModerationId  string                 `protobuf:"bytes,2,opt,name=moderation_id,json=moderationId,proto3" json:"moderation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationRequest) Reset() {
	*x = GetModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationRequest) ProtoMessage() {}

func (x *GetModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationRequest.ProtoReflect.Descriptor instead.
func (*GetModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{14}
}

func (x *GetModerationRequest) GetModerationId() string {
	if x != nil {
		return x.ModerationId
	}
	return ""
}

type GetModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *Moderation            `protobuf:"bytes,1,opt,name=Moderation,proto3" json:"Moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModerationResponse) Reset() {
	*x = GetModerationResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModerationResponse) ProtoMessage() {}

func (x *GetModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModerationResponse.ProtoReflect.Descriptor instead.
func (*GetModerationResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{15}
}

func (x *GetModerationResponse) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type UpdateModerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModerationRequest) Reset() {
	*x = UpdateModerationRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModerationRequest) ProtoMessage() {}

func (x *UpdateModerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModerationRequest.ProtoReflect.Descriptor instead.
func (*UpdateModerationRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateModerationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateModerationRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type UpdateModerationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderation    *Moderation            `protobuf:"bytes,1,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModerationResponse) Reset() {
	*x = UpdateModerationResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModerationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModerationResponse) ProtoMessage() {}

func (x *UpdateModerationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModerationResponse.ProtoReflect.Descriptor instead.
func (*UpdateModerationResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateModerationResponse) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

type MyReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyReviewsRequest) Reset() {
	*x = MyReviewsRequest{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyReviewsRequest) ProtoMessage() {}

func (x *MyReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyReviewsRequest.ProtoReflect.Descriptor instead.
func (*MyReviewsRequest) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{18}
}

func (x *MyReviewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MyReviewsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MyReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*QueueProduct        `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MyReviewsResponse) Reset() {
	*x = MyReviewsResponse{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MyReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyReviewsResponse) ProtoMessage() {}

func (x *MyReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyReviewsResponse.ProtoReflect.Descriptor instead.
func (*MyReviewsResponse) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{19}
}

func (x *MyReviewsResponse) GetProducts() []*QueueProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *MyReviewsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Moderation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       string                 `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AdminUsername string                 `protobuf:"bytes,3,opt,name=admin_username,json=adminUsername,proto3" json:"admin_username,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderation) Reset() {
	*x = Moderation{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderation) ProtoMessage() {}

func (x *Moderation) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderation.ProtoReflect.Descriptor instead.
func (*Moderation) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{20}
}

func (x *Moderation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Moderation) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *Moderation) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Moderation) GetAdminUsername() string {
	if x != nil {
		return x.AdminUsername
	}
	return ""
}

func (x *Moderation) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Moderation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Moderation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type QueueProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *v1.Product            `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Moderation    *Moderation            `protobuf:"bytes,2,opt,name=moderation,proto3" json:"moderation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueProduct) Reset() {
	*x = QueueProduct{}
	mi := &file_moderation_v1_moderation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueProduct) ProtoMessage() {}

func (x *QueueProduct) ProtoReflect() protoreflect.Message {
	mi := &file_moderation_v1_moderation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueProduct.ProtoReflect.Descriptor instead.
func (*QueueProduct) Descriptor() ([]byte, []int) {
	return file_moderation_v1_moderation_proto_rawDescGZIP(), []int{21}
}

func (x *QueueProduct) GetProduct() *v1.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *QueueProduct) GetModeration() *Moderation {
	if x != nil {
		return x.Moderation
	}
	return nil
}

var File_moderation_v1_moderation_proto protoreflect.FileDescriptor

const file_moderation_v1_moderation_proto_rawDesc = "" +
	"\n" +
	"\x1emoderation/v1/moderation.proto\x12\rmoderation.v1\x1a'googleapis/google/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18product/v1/product.proto\"\x0e\n" +
	"\fStatsRequest\"\x82\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_pending\x18\x01 \x01(\x05R\ftotalPending\x12%\n" +
	"\x0etotal_approved\x18\x02 \x01(\x05R\rtotalApproved\x12%\n" +
	"\x0etotal_rejected\x18\x03 \x01(\x05R\rtotalRejected\"F\n" +
	"\rRejectRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"?\n" +
	"\x0eRejectResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"/\n" +
	"\x0eApproveRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"@\n" +
	"\x0fApproveResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"/\n" +
	"\x0eReleaseRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x11\n" +
	"\x0fReleaseResponse\"-\n" +
	"\fClaimRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"J\n" +
	"\rClaimResponse\x129\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x19.moderation.v1.ModerationR\n" +
	"moderation\"<\n" +
	"\fQueueRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"^\n" +
	"\rQueueResponse\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.moderation.v1.QueueProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"k\n" +
	"\x17CreateModerationRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"U\n" +
	"\x18CreateModerationResponse\x129\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x19.moderation.v1.ModerationR\n" +
	"moderation\";\n" +
	"\x14GetModerationRequest\x12#\n" +
	"\rmoderation_id\x18\x02 \x01(\tR\fmoderationId\"R\n" +
	"\x15GetModerationResponse\x129\n" +
	"\n" +
	"Moderation\x18\x01 \x01(\v2\x19.moderation.v1.ModerationR\n" +
	"Moderation\"A\n" +
	"\x17UpdateModerationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"U\n" +
	"\x18UpdateModerationResponse\x129\n" +
	"\n" +
	"moderation\x18\x01 \x01(\v2\x19.moderation.v1.ModerationR\n" +
	"moderation\"@\n" +
	"\x10MyReviewsRequest\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"b\n" +
	"\x11MyReviewsResponse\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.moderation.v1.QueueProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8b\x02\n" +
	"\n" +
	"Moderation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\tR\aadminId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12%\n" +
	"\x0eadmin_username\x18\x03 \x01(\tR\radminUsername\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"x\n" +
	"\fQueueProduct\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\x129\n" +
	"\n" +
	"moderation\x18\x02 \x01(\v2\x19.moderation.v1.ModerationR\n" +
	"moderation2\x8f\t\n" +
	"\x11ModerationService\x12\x82\x01\n" +
	"\x10CreateModeration\x12&.moderation.v1.CreateModerationRequest\x1a'.moderation.v1.CreateModerationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/moderation\x12v\n" +
	"\rGetModeration\x12#.moderation.v1.GetModerationRequest\x1a$.moderation.v1.GetModerationResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/moderation\x12\x89\x01\n" +
	"\x10UpdateModeration\x12&.moderation.v1.UpdateModerationRequest\x1a'.moderation.v1.UpdateModerationResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/api/v1/moderation/update\x12m\n" +
	"\tMyReviews\x12\x1f.moderation.v1.MyReviewsRequest\x1a .moderation.v1.MyReviewsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/moderation/my\x12d\n" +
	"\x05Queue\x12\x1b.moderation.v1.QueueRequest\x1a\x1c.moderation.v1.QueueResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/moderation/queue\x12g\n" +
	"\x05Claim\x12\x1b.moderation.v1.ClaimRequest\x1a\x1c.moderation.v1.ClaimResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/moderation/claim\x12o\n" +
	"\aRelease\x12\x1d.moderation.v1.ReleaseRequest\x1a\x1e.moderation.v1.ReleaseResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/moderation/release\x12o\n" +
	"\aApprove\x12\x1d.moderation.v1.ApproveRequest\x1a\x1e.moderation.v1.ApproveResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/moderation/approve\x12k\n" +
	"\x06Reject\x12\x1c.moderation.v1.RejectRequest\x1a\x1d.moderation.v1.RejectResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/moderation/reject\x12d\n" +
	"\x05Stats\x12\x1b.moderation.v1.StatsRequest\x1a\x1c.moderation.v1.StatsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/moderation/statsBKZIgithub.com/nhassl3/servicehub-contracts/pkg/pb/moderation/v1;moderationv1b\x06proto3"

var (
	file_moderation_v1_moderation_proto_rawDescOnce sync.Once
	file_moderation_v1_moderation_proto_rawDescData []byte
)

func file_moderation_v1_moderation_proto_rawDescGZIP() []byte {
	file_moderation_v1_moderation_proto_rawDescOnce.Do(func() {
		file_moderation_v1_moderation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)))
	})
	return file_moderation_v1_moderation_proto_rawDescData
}

var file_moderation_v1_moderation_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_moderation_v1_moderation_proto_goTypes = []any{
	(*StatsRequest)(nil),             // 0: moderation.v1.StatsRequest
	(*StatsResponse)(nil),            // 1: moderation.v1.StatsResponse
	(*RejectRequest)(nil),            // 2: moderation.v1.RejectRequest
	(*RejectResponse)(nil),           // 3: moderation.v1.RejectResponse
	(*ApproveRequest)(nil),           // 4: moderation.v1.ApproveRequest
	(*ApproveResponse)(nil),          // 5: moderation.v1.ApproveResponse
	(*ReleaseRequest)(nil),           // 6: moderation.v1.ReleaseRequest
	(*ReleaseResponse)(nil),          // 7: moderation.v1.ReleaseResponse
	(*ClaimRequest)(nil),             // 8: moderation.v1.ClaimRequest
	(*ClaimResponse)(nil),            // 9: moderation.v1.ClaimResponse
	(*QueueRequest)(nil),             // 10: moderation.v1.QueueRequest
	(*QueueResponse)(nil),            // 11: moderation.v1.QueueResponse
	(*CreateModerationRequest)(nil),  // 12: moderation.v1.CreateModerationRequest
	(*CreateModerationResponse)(nil), // 13: moderation.v1.CreateModerationResponse
	(*GetModerationRequest)(nil),     // 14: moderation.v1.GetModerationRequest
	(*GetModerationResponse)(nil),    // 15: moderation.v1.GetModerationResponse
	(*UpdateModerationRequest)(nil),  // 16: moderation.v1.UpdateModerationRequest
	(*UpdateModerationResponse)(nil), // 17: moderation.v1.UpdateModerationResponse
	(*MyReviewsRequest)(nil),         // 18: moderation.v1.MyReviewsRequest
	(*MyReviewsResponse)(nil),        // 19: moderation.v1.MyReviewsResponse
	(*Moderation)(nil),               // 20: moderation.v1.Moderation
	(*QueueProduct)(nil),             // 21: moderation.v1.QueueProduct
	(*v1.Product)(nil),               // 22: product.v1.Product
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
}
var file_moderation_v1_moderation_proto_depIdxs = []int32{
	22, // 0: moderation.v1.RejectResponse.product:type_name -> product.v1.Product
	22, // 1: moderation.v1.ApproveResponse.product:type_name -> product.v1.Product
	20, // 2: moderation.v1.ClaimResponse.moderation:type_name -> moderation.v1.Moderation
	21, // 3: moderation.v1.QueueResponse.products:type_name -> moderation.v1.QueueProduct
	20, // 4: moderation.v1.CreateModerationResponse.moderation:type_name -> moderation.v1.Moderation
	20, // 5: moderation.v1.GetModerationResponse.Moderation:type_name -> moderation.v1.Moderation
	20, // 6: moderation.v1.UpdateModerationResponse.moderation:type_name -> moderation.v1.Moderation
	21, // 7: moderation.v1.MyReviewsResponse.products:type_name -> moderation.v1.QueueProduct
	23, // 8: moderation.v1.Moderation.created_at:type_name -> google.protobuf.Timestamp
	23, // 9: moderation.v1.Moderation.updated_at:type_name -> google.protobuf.Timestamp
	22, // 10: moderation.v1.QueueProduct.product:type_name -> product.v1.Product
	20, // 11: moderation.v1.QueueProduct.moderation:type_name -> moderation.v1.Moderation
	12, // 12: moderation.v1.ModerationService.CreateModeration:input_type -> moderation.v1.CreateModerationRequest
	14, // 13: moderation.v1.ModerationService.GetModeration:input_type -> moderation.v1.GetModerationRequest
	16, // 14: moderation.v1.ModerationService.UpdateModeration:input_type -> moderation.v1.UpdateModerationRequest
	18, // 15: moderation.v1.ModerationService.MyReviews:input_type -> moderation.v1.MyReviewsRequest
	10, // 16: moderation.v1.ModerationService.Queue:input_type -> moderation.v1.QueueRequest
	8,  // 17: moderation.v1.ModerationService.Claim:input_type -> moderation.v1.ClaimRequest
	6,  // 18: moderation.v1.ModerationService.Release:input_type -> moderation.v1.ReleaseRequest
	4,  // 19: moderation.v1.ModerationService.Approve:input_type -> moderation.v1.ApproveRequest
	2,  // 20: moderation.v1.ModerationService.Reject:input_type -> moderation.v1.RejectRequest
	0,  // 21: moderation.v1.ModerationService.Stats:input_type -> moderation.v1.StatsRequest
	13, // 22: moderation.v1.ModerationService.CreateModeration:output_type -> moderation.v1.CreateModerationResponse
	15, // 23: moderation.v1.ModerationService.GetModeration:output_type -> moderation.v1.GetModerationResponse
	17, // 24: moderation.v1.ModerationService.UpdateModeration:output_type -> moderation.v1.UpdateModerationResponse
	19, // 25: moderation.v1.ModerationService.MyReviews:output_type -> moderation.v1.MyReviewsResponse
	11, // 26: moderation.v1.ModerationService.Queue:output_type -> moderation.v1.QueueResponse
	9,  // 27: moderation.v1.ModerationService.Claim:output_type -> moderation.v1.ClaimResponse
	7,  // 28: moderation.v1.ModerationService.Release:output_type -> moderation.v1.ReleaseResponse
	5,  // 29: moderation.v1.ModerationService.Approve:output_type -> moderation.v1.ApproveResponse
	3,  // 30: moderation.v1.ModerationService.Reject:output_type -> moderation.v1.RejectResponse
	1,  // 31: moderation.v1.ModerationService.Stats:output_type -> moderation.v1.StatsResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_moderation_v1_moderation_proto_init() }
func file_moderation_v1_moderation_proto_init() {
	if File_moderation_v1_moderation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moderation_v1_moderation_proto_rawDesc), len(file_moderation_v1_moderation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moderation_v1_moderation_proto_goTypes,
		DependencyIndexes: file_moderation_v1_moderation_proto_depIdxs,
		MessageInfos:      file_moderation_v1_moderation_proto_msgTypes,
	}.Build()
	File_moderation_v1_moderation_proto = out.File
	file_moderation_v1_moderation_proto_goTypes = nil
	file_moderation_v1_moderation_proto_depIdxs = nil
}
