// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package moderationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ModerationServiceClient is the client API for ModerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModerationServiceClient interface {
	CreateModeration(ctx context.Context, in *CreateModerationRequest, opts ...grpc.CallOption) (*CreateModerationResponse, error)
	GetModeration(ctx context.Context, in *GetModerationRequest, opts ...grpc.CallOption) (*GetModerationResponse, error)
	UpdateModeration(ctx context.Context, in *UpdateModerationRequest, opts ...grpc.CallOption) (*UpdateModerationResponse, error)
	MyReviews(ctx context.Context, in *MyReviewsRequest, opts ...grpc.CallOption) (*MyReviewsResponse, error)
	Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error)
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error)
	Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*RejectResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type moderationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModerationServiceClient(cc grpc.ClientConnInterface) ModerationServiceClient {
	return &moderationServiceClient{cc}
}

func (c *moderationServiceClient) CreateModeration(ctx context.Context, in *CreateModerationRequest, opts ...grpc.CallOption) (*CreateModerationResponse, error) {
	out := new(CreateModerationResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/CreateModeration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) GetModeration(ctx context.Context, in *GetModerationRequest, opts ...grpc.CallOption) (*GetModerationResponse, error) {
	out := new(GetModerationResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/GetModeration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) UpdateModeration(ctx context.Context, in *UpdateModerationRequest, opts ...grpc.CallOption) (*UpdateModerationResponse, error) {
	out := new(UpdateModerationResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/UpdateModeration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) MyReviews(ctx context.Context, in *MyReviewsRequest, opts ...grpc.CallOption) (*MyReviewsResponse, error) {
	out := new(MyReviewsResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/MyReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Queue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Queue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Claim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Approve(ctx context.Context, in *ApproveRequest, opts ...grpc.CallOption) (*ApproveResponse, error) {
	out := new(ApproveResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Approve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Reject(ctx context.Context, in *RejectRequest, opts ...grpc.CallOption) (*RejectResponse, error) {
	out := new(RejectResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Reject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderationServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/moderation.v1.ModerationService/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModerationServiceServer is the server API for ModerationService service.
// All implementations must embed UnimplementedModerationServiceServer
// for forward compatibility
type ModerationServiceServer interface {
	CreateModeration(context.Context, *CreateModerationRequest) (*CreateModerationResponse, error)
	GetModeration(context.Context, *GetModerationRequest) (*GetModerationResponse, error)
	UpdateModeration(context.Context, *UpdateModerationRequest) (*UpdateModerationResponse, error)
	MyReviews(context.Context, *MyReviewsRequest) (*MyReviewsResponse, error)
	Queue(context.Context, *QueueRequest) (*QueueResponse, error)
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	Approve(context.Context, *ApproveRequest) (*ApproveResponse, error)
	Reject(context.Context, *RejectRequest) (*RejectResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedModerationServiceServer()
}

// UnimplementedModerationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedModerationServiceServer struct {
}

func (UnimplementedModerationServiceServer) CreateModeration(context.Context, *CreateModerationRequest) (*CreateModerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModeration not implemented")
}
func (UnimplementedModerationServiceServer) GetModeration(context.Context, *GetModerationRequest) (*GetModerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModeration not implemented")
}
func (UnimplementedModerationServiceServer) UpdateModeration(context.Context, *UpdateModerationRequest) (*UpdateModerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModeration not implemented")
}
func (UnimplementedModerationServiceServer) MyReviews(context.Context, *MyReviewsRequest) (*MyReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MyReviews not implemented")
}
func (UnimplementedModerationServiceServer) Queue(context.Context, *QueueRequest) (*QueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Queue not implemented")
}
func (UnimplementedModerationServiceServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedModerationServiceServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedModerationServiceServer) Approve(context.Context, *ApproveRequest) (*ApproveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Approve not implemented")
}
func (UnimplementedModerationServiceServer) Reject(context.Context, *RejectRequest) (*RejectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reject not implemented")
}
func (UnimplementedModerationServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedModerationServiceServer) mustEmbedUnimplementedModerationServiceServer() {}

// UnsafeModerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModerationServiceServer will
// result in compilation errors.
type UnsafeModerationServiceServer interface {
	mustEmbedUnimplementedModerationServiceServer()
}

func RegisterModerationServiceServer(s *grpc.Server, srv ModerationServiceServer) {
	s.RegisterService(&_ModerationService_serviceDesc, srv)
}

func _ModerationService_CreateModeration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).CreateModeration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/CreateModeration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).CreateModeration(ctx, req.(*CreateModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_GetModeration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).GetModeration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/GetModeration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).GetModeration(ctx, req.(*GetModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_UpdateModeration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).UpdateModeration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/UpdateModeration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).UpdateModeration(ctx, req.(*UpdateModerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_MyReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).MyReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/MyReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).MyReviews(ctx, req.(*MyReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Queue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Queue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Queue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Queue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Claim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Approve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Approve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Approve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Approve(ctx, req.(*ApproveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Reject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Reject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Reject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Reject(ctx, req.(*RejectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModerationService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModerationServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moderation.v1.ModerationService/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModerationServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ModerationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moderation.v1.ModerationService",
	HandlerType: (*ModerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateModeration",
			Handler:    _ModerationService_CreateModeration_Handler,
		},
		{
			MethodName: "GetModeration",
			Handler:    _ModerationService_GetModeration_Handler,
		},
		{
			MethodName: "UpdateModeration",
			Handler:    _ModerationService_UpdateModeration_Handler,
		},
		{
			MethodName: "MyReviews",
			Handler:    _ModerationService_MyReviews_Handler,
		},
		{
			MethodName: "Queue",
			Handler:    _ModerationService_Queue_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _ModerationService_Claim_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _ModerationService_Release_Handler,
		},
		{
			MethodName: "Approve",
			Handler:    _ModerationService_Approve_Handler,
		},
		{
			MethodName: "Reject",
			Handler:    _ModerationService_Reject_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _ModerationService_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moderation/v1/moderation.proto",
}
