// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: review/v1/review.proto

package reviewv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *ListReviewsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListReviewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListReviewsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListReviewsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReviewRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReviewRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_review_v1_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{6}
}

func (x *Review) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Review) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Review) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_review_v1_review_proto protoreflect.FileDescriptor

const file_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x16review/v1/review.proto\x12\treview.v1\x1a'googleapis/google/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\x12ListReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"X\n" +
	"\x13ListReviewsResponse\x12+\n" +
	"\areviews\x18\x01 \x03(\v2\x11.review.v1.ReviewR\areviews\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"f\n" +
	"\x13CreateReviewRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"A\n" +
	"\x14CreateReviewResponse\x12)\n" +
	"\x06review\x18\x01 \x01(\v2\x11.review.v1.ReviewR\x06review\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x14DeleteReviewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc0\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xff\x02\n" +
	"\rReviewService\x12{\n" +
	"\vListReviews\x12\x1d.review.v1.ListReviewsRequest\x1a\x1e.review.v1.ListReviewsResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/v1/products/{product_id}/reviews\x12\x81\x01\n" +
	"\fCreateReview\x12\x1e.review.v1.CreateReviewRequest\x1a\x1f.review.v1.CreateReviewResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/products/{product_id}/reviews\x12m\n" +
	"\fDeleteReview\x12\x1e.review.v1.DeleteReviewRequest\x1a\x1f.review.v1.DeleteReviewResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/reviews/{id}BCZAgithub.com/nhassl3/servicehub-contracts/pkg/pb/review/v1;reviewv1b\x06proto3"

var (
	file_review_v1_review_proto_rawDescOnce sync.Once
	file_review_v1_review_proto_rawDescData []byte
)

func file_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)))
	})
	return file_review_v1_review_proto_rawDescData
}

var file_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_review_v1_review_proto_goTypes = []any{
	(*ListReviewsRequest)(nil),    // 0: review.v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),   // 1: review.v1.ListReviewsResponse
	(*CreateReviewRequest)(nil),   // 2: review.v1.CreateReviewRequest
	(*CreateReviewResponse)(nil),  // 3: review.v1.CreateReviewResponse
	(*DeleteReviewRequest)(nil),   // 4: review.v1.DeleteReviewRequest
	(*DeleteReviewResponse)(nil),  // 5: review.v1.DeleteReviewResponse
	(*Review)(nil),                // 6: review.v1.Review
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_review_v1_review_proto_depIdxs = []int32{
	6, // 0: review.v1.ListReviewsResponse.reviews:type_name -> review.v1.Review
	6, // 1: review.v1.CreateReviewResponse.review:type_name -> review.v1.Review
	7, // 2: review.v1.Review.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: review.v1.ReviewService.ListReviews:input_type -> review.v1.ListReviewsRequest
	2, // 4: review.v1.ReviewService.CreateReview:input_type -> review.v1.CreateReviewRequest
	4, // 5: review.v1.ReviewService.DeleteReview:input_type -> review.v1.DeleteReviewRequest
	1, // 6: review.v1.ReviewService.ListReviews:output_type -> review.v1.ListReviewsResponse
	3, // 7: review.v1.ReviewService.CreateReview:output_type -> review.v1.CreateReviewResponse
	5, // 8: review.v1.ReviewService.DeleteReview:output_type -> review.v1.DeleteReviewResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_review_v1_review_proto_init() }
func file_review_v1_review_proto_init() {
	if File_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_v1_review_proto = out.File
	file_review_v1_review_proto_goTypes = nil
	file_review_v1_review_proto_depIdxs = nil
}
