// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/admin.proto

package adminv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateAdminRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAdminRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAdminRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAdminRequestMultiError, or nil if none found.
func (m *CreateAdminRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAdminRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	if m.LevelRights != nil {
		// no validation rules for LevelRights
	}

	if len(errors) > 0 {
		return CreateAdminRequestMultiError(errors)
	}

	return nil
}

// CreateAdminRequestMultiError is an error wrapping multiple validation errors
// returned by CreateAdminRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateAdminRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAdminRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAdminRequestMultiError) AllErrors() []error { return m }

// CreateAdminRequestValidationError is the validation error returned by
// CreateAdminRequest.Validate if the designated constraints aren't met.
type CreateAdminRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAdminRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAdminRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAdminRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAdminRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAdminRequestValidationError) ErrorName() string {
	return "CreateAdminRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAdminRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAdminRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAdminRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAdminRequestValidationError{}

// Validate checks the field values on CreateAdminResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAdminResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAdminResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAdminResponseMultiError, or nil if none found.
func (m *CreateAdminResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAdminResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAdmin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateAdminResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateAdminResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAdmin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateAdminResponseValidationError{
				field:  "Admin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateAdminResponseMultiError(errors)
	}

	return nil
}

// CreateAdminResponseMultiError is an error wrapping multiple validation
// errors returned by CreateAdminResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateAdminResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAdminResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAdminResponseMultiError) AllErrors() []error { return m }

// CreateAdminResponseValidationError is the validation error returned by
// CreateAdminResponse.Validate if the designated constraints aren't met.
type CreateAdminResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAdminResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAdminResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAdminResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAdminResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAdminResponseValidationError) ErrorName() string {
	return "CreateAdminResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAdminResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAdminResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAdminResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAdminResponseValidationError{}

// Validate checks the field values on GetAdminProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAdminProfileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAdminProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAdminProfileRequestMultiError, or nil if none found.
func (m *GetAdminProfileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAdminProfileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Username != nil {
		// no validation rules for Username
	}

	if m.Id != nil {
		// no validation rules for Id
	}

	if len(errors) > 0 {
		return GetAdminProfileRequestMultiError(errors)
	}

	return nil
}

// GetAdminProfileRequestMultiError is an error wrapping multiple validation
// errors returned by GetAdminProfileRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAdminProfileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAdminProfileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAdminProfileRequestMultiError) AllErrors() []error { return m }

// GetAdminProfileRequestValidationError is the validation error returned by
// GetAdminProfileRequest.Validate if the designated constraints aren't met.
type GetAdminProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAdminProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAdminProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAdminProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAdminProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAdminProfileRequestValidationError) ErrorName() string {
	return "GetAdminProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAdminProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAdminProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAdminProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAdminProfileRequestValidationError{}

// Validate checks the field values on GetAdminProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAdminProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAdminProfileResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAdminProfileResponseMultiError, or nil if none found.
func (m *GetAdminProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAdminProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAdmin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAdminProfileResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAdminProfileResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAdmin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAdminProfileResponseValidationError{
				field:  "Admin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAdminProfileResponseMultiError(errors)
	}

	return nil
}

// GetAdminProfileResponseMultiError is an error wrapping multiple validation
// errors returned by GetAdminProfileResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAdminProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAdminProfileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAdminProfileResponseMultiError) AllErrors() []error { return m }

// GetAdminProfileResponseValidationError is the validation error returned by
// GetAdminProfileResponse.Validate if the designated constraints aren't met.
type GetAdminProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAdminProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAdminProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAdminProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAdminProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAdminProfileResponseValidationError) ErrorName() string {
	return "GetAdminProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAdminProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAdminProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAdminProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAdminProfileResponseValidationError{}

// Validate checks the field values on GetModeratedProductsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModeratedProductsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModeratedProductsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModeratedProductsRequestMultiError, or nil if none found.
func (m *GetModeratedProductsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModeratedProductsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetModeratedProductsRequestMultiError(errors)
	}

	return nil
}

// GetModeratedProductsRequestMultiError is an error wrapping multiple
// validation errors returned by GetModeratedProductsRequest.ValidateAll() if
// the designated constraints aren't met.
type GetModeratedProductsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModeratedProductsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModeratedProductsRequestMultiError) AllErrors() []error { return m }

// GetModeratedProductsRequestValidationError is the validation error returned
// by GetModeratedProductsRequest.Validate if the designated constraints
// aren't met.
type GetModeratedProductsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModeratedProductsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModeratedProductsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModeratedProductsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModeratedProductsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModeratedProductsRequestValidationError) ErrorName() string {
	return "GetModeratedProductsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetModeratedProductsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModeratedProductsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModeratedProductsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModeratedProductsRequestValidationError{}

// Validate checks the field values on GetModeratedProductsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetModeratedProductsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetModeratedProductsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetModeratedProductsResponseMultiError, or nil if none found.
func (m *GetModeratedProductsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetModeratedProductsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetProducts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetModeratedProductsResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetModeratedProductsResponseValidationError{
						field:  fmt.Sprintf("Products[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetModeratedProductsResponseValidationError{
					field:  fmt.Sprintf("Products[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetModeratedProductsResponseMultiError(errors)
	}

	return nil
}

// GetModeratedProductsResponseMultiError is an error wrapping multiple
// validation errors returned by GetModeratedProductsResponse.ValidateAll() if
// the designated constraints aren't met.
type GetModeratedProductsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetModeratedProductsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetModeratedProductsResponseMultiError) AllErrors() []error { return m }

// GetModeratedProductsResponseValidationError is the validation error returned
// by GetModeratedProductsResponse.Validate if the designated constraints
// aren't met.
type GetModeratedProductsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetModeratedProductsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetModeratedProductsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetModeratedProductsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetModeratedProductsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetModeratedProductsResponseValidationError) ErrorName() string {
	return "GetModeratedProductsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetModeratedProductsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetModeratedProductsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetModeratedProductsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetModeratedProductsResponseValidationError{}

// Validate checks the field values on UpdateAdminProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateAdminProfileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAdminProfileRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateAdminProfileRequestMultiError, or nil if none found.
func (m *UpdateAdminProfileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAdminProfileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.DisplayName != nil {
		// no validation rules for DisplayName
	}

	if m.AvatarUrl != nil {
		// no validation rules for AvatarUrl
	}

	if m.LevelRights != nil {
		// no validation rules for LevelRights
	}

	if m.TotalModeration != nil {
		// no validation rules for TotalModeration
	}

	if len(errors) > 0 {
		return UpdateAdminProfileRequestMultiError(errors)
	}

	return nil
}

// UpdateAdminProfileRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateAdminProfileRequest.ValidateAll() if the
// designated constraints aren't met.
type UpdateAdminProfileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAdminProfileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAdminProfileRequestMultiError) AllErrors() []error { return m }

// UpdateAdminProfileRequestValidationError is the validation error returned by
// UpdateAdminProfileRequest.Validate if the designated constraints aren't met.
type UpdateAdminProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAdminProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAdminProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAdminProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAdminProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAdminProfileRequestValidationError) ErrorName() string {
	return "UpdateAdminProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAdminProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAdminProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAdminProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAdminProfileRequestValidationError{}

// Validate checks the field values on UpdateAdminProfileResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateAdminProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAdminProfileResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateAdminProfileResponseMultiError, or nil if none found.
func (m *UpdateAdminProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAdminProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAdmin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateAdminProfileResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateAdminProfileResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAdmin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateAdminProfileResponseValidationError{
				field:  "Admin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateAdminProfileResponseMultiError(errors)
	}

	return nil
}

// UpdateAdminProfileResponseMultiError is an error wrapping multiple
// validation errors returned by UpdateAdminProfileResponse.ValidateAll() if
// the designated constraints aren't met.
type UpdateAdminProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAdminProfileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAdminProfileResponseMultiError) AllErrors() []error { return m }

// UpdateAdminProfileResponseValidationError is the validation error returned
// by UpdateAdminProfileResponse.Validate if the designated constraints aren't met.
type UpdateAdminProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAdminProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAdminProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAdminProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAdminProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAdminProfileResponseValidationError) ErrorName() string {
	return "UpdateAdminProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAdminProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAdminProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAdminProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAdminProfileResponseValidationError{}

// Validate checks the field values on IncreaseAdminModeratesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IncreaseAdminModeratesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IncreaseAdminModeratesRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// IncreaseAdminModeratesRequestMultiError, or nil if none found.
func (m *IncreaseAdminModeratesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IncreaseAdminModeratesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalModeration

	if len(errors) > 0 {
		return IncreaseAdminModeratesRequestMultiError(errors)
	}

	return nil
}

// IncreaseAdminModeratesRequestMultiError is an error wrapping multiple
// validation errors returned by IncreaseAdminModeratesRequest.ValidateAll()
// if the designated constraints aren't met.
type IncreaseAdminModeratesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IncreaseAdminModeratesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IncreaseAdminModeratesRequestMultiError) AllErrors() []error { return m }

// IncreaseAdminModeratesRequestValidationError is the validation error
// returned by IncreaseAdminModeratesRequest.Validate if the designated
// constraints aren't met.
type IncreaseAdminModeratesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IncreaseAdminModeratesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IncreaseAdminModeratesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IncreaseAdminModeratesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IncreaseAdminModeratesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IncreaseAdminModeratesRequestValidationError) ErrorName() string {
	return "IncreaseAdminModeratesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e IncreaseAdminModeratesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIncreaseAdminModeratesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IncreaseAdminModeratesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IncreaseAdminModeratesRequestValidationError{}

// Validate checks the field values on IncreaseAdminModeratesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IncreaseAdminModeratesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IncreaseAdminModeratesResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// IncreaseAdminModeratesResponseMultiError, or nil if none found.
func (m *IncreaseAdminModeratesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IncreaseAdminModeratesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return IncreaseAdminModeratesResponseMultiError(errors)
	}

	return nil
}

// IncreaseAdminModeratesResponseMultiError is an error wrapping multiple
// validation errors returned by IncreaseAdminModeratesResponse.ValidateAll()
// if the designated constraints aren't met.
type IncreaseAdminModeratesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IncreaseAdminModeratesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IncreaseAdminModeratesResponseMultiError) AllErrors() []error { return m }

// IncreaseAdminModeratesResponseValidationError is the validation error
// returned by IncreaseAdminModeratesResponse.Validate if the designated
// constraints aren't met.
type IncreaseAdminModeratesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IncreaseAdminModeratesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IncreaseAdminModeratesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IncreaseAdminModeratesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IncreaseAdminModeratesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IncreaseAdminModeratesResponseValidationError) ErrorName() string {
	return "IncreaseAdminModeratesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e IncreaseAdminModeratesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIncreaseAdminModeratesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IncreaseAdminModeratesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IncreaseAdminModeratesResponseValidationError{}

// Validate checks the field values on UploadAvatarRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadAvatarRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadAvatarRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadAvatarRequestMultiError, or nil if none found.
func (m *UploadAvatarRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadAvatarRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FileData

	// no validation rules for ContentType

	if len(errors) > 0 {
		return UploadAvatarRequestMultiError(errors)
	}

	return nil
}

// UploadAvatarRequestMultiError is an error wrapping multiple validation
// errors returned by UploadAvatarRequest.ValidateAll() if the designated
// constraints aren't met.
type UploadAvatarRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadAvatarRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadAvatarRequestMultiError) AllErrors() []error { return m }

// UploadAvatarRequestValidationError is the validation error returned by
// UploadAvatarRequest.Validate if the designated constraints aren't met.
type UploadAvatarRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarRequestValidationError) ErrorName() string {
	return "UploadAvatarRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarRequestValidationError{}

// Validate checks the field values on UploadAvatarResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadAvatarResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadAvatarResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadAvatarResponseMultiError, or nil if none found.
func (m *UploadAvatarResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadAvatarResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAdmin()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UploadAvatarResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UploadAvatarResponseValidationError{
					field:  "Admin",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAdmin()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UploadAvatarResponseValidationError{
				field:  "Admin",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UploadAvatarResponseMultiError(errors)
	}

	return nil
}

// UploadAvatarResponseMultiError is an error wrapping multiple validation
// errors returned by UploadAvatarResponse.ValidateAll() if the designated
// constraints aren't met.
type UploadAvatarResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadAvatarResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadAvatarResponseMultiError) AllErrors() []error { return m }

// UploadAvatarResponseValidationError is the validation error returned by
// UploadAvatarResponse.Validate if the designated constraints aren't met.
type UploadAvatarResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarResponseValidationError) ErrorName() string {
	return "UploadAvatarResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarResponseValidationError{}

// Validate checks the field values on AdminProfile with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AdminProfile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AdminProfile with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AdminProfileMultiError, or
// nil if none found.
func (m *AdminProfile) ValidateAll() error {
	return m.validate(true)
}

func (m *AdminProfile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for DisplayName

	// no validation rules for LevelRights

	// no validation rules for TotalModeration

	// no validation rules for AvatarUrl

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AdminProfileValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AdminProfileValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AdminProfileValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AdminProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AdminProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AdminProfileValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AdminProfileMultiError(errors)
	}

	return nil
}

// AdminProfileMultiError is an error wrapping multiple validation errors
// returned by AdminProfile.ValidateAll() if the designated constraints aren't met.
type AdminProfileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AdminProfileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AdminProfileMultiError) AllErrors() []error { return m }

// AdminProfileValidationError is the validation error returned by
// AdminProfile.Validate if the designated constraints aren't met.
type AdminProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AdminProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AdminProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AdminProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AdminProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AdminProfileValidationError) ErrorName() string { return "AdminProfileValidationError" }

// Error satisfies the builtin error interface
func (e AdminProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAdminProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AdminProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AdminProfileValidationError{}
