// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: seller/v1/seller.proto

package sellerv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateSellerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSellerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSellerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSellerRequestMultiError, or nil if none found.
func (m *CreateSellerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSellerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	// no validation rules for Description

	if len(errors) > 0 {
		return CreateSellerRequestMultiError(errors)
	}

	return nil
}

// CreateSellerRequestMultiError is an error wrapping multiple validation
// errors returned by CreateSellerRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateSellerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSellerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSellerRequestMultiError) AllErrors() []error { return m }

// CreateSellerRequestValidationError is the validation error returned by
// CreateSellerRequest.Validate if the designated constraints aren't met.
type CreateSellerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSellerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSellerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSellerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSellerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSellerRequestValidationError) ErrorName() string {
	return "CreateSellerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSellerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSellerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSellerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSellerRequestValidationError{}

// Validate checks the field values on CreateSellerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSellerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSellerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSellerResponseMultiError, or nil if none found.
func (m *CreateSellerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSellerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSeller()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateSellerResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateSellerResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSeller()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateSellerResponseValidationError{
				field:  "Seller",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateSellerResponseMultiError(errors)
	}

	return nil
}

// CreateSellerResponseMultiError is an error wrapping multiple validation
// errors returned by CreateSellerResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateSellerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSellerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSellerResponseMultiError) AllErrors() []error { return m }

// CreateSellerResponseValidationError is the validation error returned by
// CreateSellerResponse.Validate if the designated constraints aren't met.
type CreateSellerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSellerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSellerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSellerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSellerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSellerResponseValidationError) ErrorName() string {
	return "CreateSellerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSellerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSellerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSellerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSellerResponseValidationError{}

// Validate checks the field values on GetSellerProfileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSellerProfileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSellerProfileRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSellerProfileRequestMultiError, or nil if none found.
func (m *GetSellerProfileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSellerProfileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.Username != nil {
		// no validation rules for Username
	}

	if m.SellerId != nil {
		// no validation rules for SellerId
	}

	if len(errors) > 0 {
		return GetSellerProfileRequestMultiError(errors)
	}

	return nil
}

// GetSellerProfileRequestMultiError is an error wrapping multiple validation
// errors returned by GetSellerProfileRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSellerProfileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSellerProfileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSellerProfileRequestMultiError) AllErrors() []error { return m }

// GetSellerProfileRequestValidationError is the validation error returned by
// GetSellerProfileRequest.Validate if the designated constraints aren't met.
type GetSellerProfileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSellerProfileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSellerProfileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSellerProfileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSellerProfileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSellerProfileRequestValidationError) ErrorName() string {
	return "GetSellerProfileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSellerProfileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSellerProfileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSellerProfileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSellerProfileRequestValidationError{}

// Validate checks the field values on GetSellerProfileResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSellerProfileResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSellerProfileResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSellerProfileResponseMultiError, or nil if none found.
func (m *GetSellerProfileResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSellerProfileResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSeller()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSellerProfileResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSellerProfileResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSeller()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSellerProfileResponseValidationError{
				field:  "Seller",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSellerProfileResponseMultiError(errors)
	}

	return nil
}

// GetSellerProfileResponseMultiError is an error wrapping multiple validation
// errors returned by GetSellerProfileResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSellerProfileResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSellerProfileResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSellerProfileResponseMultiError) AllErrors() []error { return m }

// GetSellerProfileResponseValidationError is the validation error returned by
// GetSellerProfileResponse.Validate if the designated constraints aren't met.
type GetSellerProfileResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSellerProfileResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSellerProfileResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSellerProfileResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSellerProfileResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSellerProfileResponseValidationError) ErrorName() string {
	return "GetSellerProfileResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSellerProfileResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSellerProfileResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSellerProfileResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSellerProfileResponseValidationError{}

// Validate checks the field values on UpdateSellerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSellerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSellerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSellerRequestMultiError, or nil if none found.
func (m *UpdateSellerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSellerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	// no validation rules for Description

	// no validation rules for AvatarUrl

	if len(errors) > 0 {
		return UpdateSellerRequestMultiError(errors)
	}

	return nil
}

// UpdateSellerRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateSellerRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateSellerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSellerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSellerRequestMultiError) AllErrors() []error { return m }

// UpdateSellerRequestValidationError is the validation error returned by
// UpdateSellerRequest.Validate if the designated constraints aren't met.
type UpdateSellerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSellerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSellerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSellerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSellerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSellerRequestValidationError) ErrorName() string {
	return "UpdateSellerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSellerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSellerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSellerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSellerRequestValidationError{}

// Validate checks the field values on UpdateSellerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateSellerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateSellerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateSellerResponseMultiError, or nil if none found.
func (m *UpdateSellerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateSellerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSeller()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateSellerResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateSellerResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSeller()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateSellerResponseValidationError{
				field:  "Seller",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateSellerResponseMultiError(errors)
	}

	return nil
}

// UpdateSellerResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateSellerResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateSellerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateSellerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateSellerResponseMultiError) AllErrors() []error { return m }

// UpdateSellerResponseValidationError is the validation error returned by
// UpdateSellerResponse.Validate if the designated constraints aren't met.
type UpdateSellerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateSellerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateSellerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateSellerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateSellerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateSellerResponseValidationError) ErrorName() string {
	return "UpdateSellerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateSellerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateSellerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateSellerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateSellerResponseValidationError{}

// Validate checks the field values on UploadAvatarRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadAvatarRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadAvatarRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadAvatarRequestMultiError, or nil if none found.
func (m *UploadAvatarRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadAvatarRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FileData

	// no validation rules for ContentType

	if len(errors) > 0 {
		return UploadAvatarRequestMultiError(errors)
	}

	return nil
}

// UploadAvatarRequestMultiError is an error wrapping multiple validation
// errors returned by UploadAvatarRequest.ValidateAll() if the designated
// constraints aren't met.
type UploadAvatarRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadAvatarRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadAvatarRequestMultiError) AllErrors() []error { return m }

// UploadAvatarRequestValidationError is the validation error returned by
// UploadAvatarRequest.Validate if the designated constraints aren't met.
type UploadAvatarRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarRequestValidationError) ErrorName() string {
	return "UploadAvatarRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarRequestValidationError{}

// Validate checks the field values on UploadAvatarResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadAvatarResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadAvatarResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadAvatarResponseMultiError, or nil if none found.
func (m *UploadAvatarResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadAvatarResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSeller()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UploadAvatarResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UploadAvatarResponseValidationError{
					field:  "Seller",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSeller()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UploadAvatarResponseValidationError{
				field:  "Seller",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UploadAvatarResponseMultiError(errors)
	}

	return nil
}

// UploadAvatarResponseMultiError is an error wrapping multiple validation
// errors returned by UploadAvatarResponse.ValidateAll() if the designated
// constraints aren't met.
type UploadAvatarResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadAvatarResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadAvatarResponseMultiError) AllErrors() []error { return m }

// UploadAvatarResponseValidationError is the validation error returned by
// UploadAvatarResponse.Validate if the designated constraints aren't met.
type UploadAvatarResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadAvatarResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadAvatarResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadAvatarResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadAvatarResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadAvatarResponseValidationError) ErrorName() string {
	return "UploadAvatarResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UploadAvatarResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadAvatarResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadAvatarResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadAvatarResponseValidationError{}

// Validate checks the field values on SellerProfile with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SellerProfile) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SellerProfile with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SellerProfileMultiError, or
// nil if none found.
func (m *SellerProfile) ValidateAll() error {
	return m.validate(true)
}

func (m *SellerProfile) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for DisplayName

	// no validation rules for Description

	// no validation rules for AvatarUrl

	// no validation rules for Rating

	// no validation rules for TotalSales

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SellerProfileValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SellerProfileValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SellerProfileValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SellerProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SellerProfileValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SellerProfileValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SellerProfileMultiError(errors)
	}

	return nil
}

// SellerProfileMultiError is an error wrapping multiple validation errors
// returned by SellerProfile.ValidateAll() if the designated constraints
// aren't met.
type SellerProfileMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SellerProfileMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SellerProfileMultiError) AllErrors() []error { return m }

// SellerProfileValidationError is the validation error returned by
// SellerProfile.Validate if the designated constraints aren't met.
type SellerProfileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SellerProfileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SellerProfileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SellerProfileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SellerProfileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SellerProfileValidationError) ErrorName() string { return "SellerProfileValidationError" }

// Error satisfies the builtin error interface
func (e SellerProfileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSellerProfile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SellerProfileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SellerProfileValidationError{}
