// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sellerv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SellerServiceClient is the client API for SellerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SellerServiceClient interface {
	CreateSeller(ctx context.Context, in *CreateSellerRequest, opts ...grpc.CallOption) (*CreateSellerResponse, error)
	GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*GetSellerProfileResponse, error)
	UpdateSeller(ctx context.Context, in *UpdateSellerRequest, opts ...grpc.CallOption) (*UpdateSellerResponse, error)
}

type sellerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSellerServiceClient(cc grpc.ClientConnInterface) SellerServiceClient {
	return &sellerServiceClient{cc}
}

func (c *sellerServiceClient) CreateSeller(ctx context.Context, in *CreateSellerRequest, opts ...grpc.CallOption) (*CreateSellerResponse, error) {
	out := new(CreateSellerResponse)
	err := c.cc.Invoke(ctx, "/seller.v1.SellerService/CreateSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) GetSellerProfile(ctx context.Context, in *GetSellerProfileRequest, opts ...grpc.CallOption) (*GetSellerProfileResponse, error) {
	out := new(GetSellerProfileResponse)
	err := c.cc.Invoke(ctx, "/seller.v1.SellerService/GetSellerProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sellerServiceClient) UpdateSeller(ctx context.Context, in *UpdateSellerRequest, opts ...grpc.CallOption) (*UpdateSellerResponse, error) {
	out := new(UpdateSellerResponse)
	err := c.cc.Invoke(ctx, "/seller.v1.SellerService/UpdateSeller", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SellerServiceServer is the server API for SellerService service.
// All implementations must embed UnimplementedSellerServiceServer
// for forward compatibility
type SellerServiceServer interface {
	CreateSeller(context.Context, *CreateSellerRequest) (*CreateSellerResponse, error)
	GetSellerProfile(context.Context, *GetSellerProfileRequest) (*GetSellerProfileResponse, error)
	UpdateSeller(context.Context, *UpdateSellerRequest) (*UpdateSellerResponse, error)
	mustEmbedUnimplementedSellerServiceServer()
}

// UnimplementedSellerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSellerServiceServer struct {
}

func (UnimplementedSellerServiceServer) CreateSeller(context.Context, *CreateSellerRequest) (*CreateSellerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSeller not implemented")
}
func (UnimplementedSellerServiceServer) GetSellerProfile(context.Context, *GetSellerProfileRequest) (*GetSellerProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerProfile not implemented")
}
func (UnimplementedSellerServiceServer) UpdateSeller(context.Context, *UpdateSellerRequest) (*UpdateSellerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSeller not implemented")
}
func (UnimplementedSellerServiceServer) mustEmbedUnimplementedSellerServiceServer() {}

// UnsafeSellerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SellerServiceServer will
// result in compilation errors.
type UnsafeSellerServiceServer interface {
	mustEmbedUnimplementedSellerServiceServer()
}

func RegisterSellerServiceServer(s *grpc.Server, srv SellerServiceServer) {
	s.RegisterService(&_SellerService_serviceDesc, srv)
}

func _SellerService_CreateSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).CreateSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seller.v1.SellerService/CreateSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).CreateSeller(ctx, req.(*CreateSellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_GetSellerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).GetSellerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seller.v1.SellerService/GetSellerProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).GetSellerProfile(ctx, req.(*GetSellerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SellerService_UpdateSeller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SellerServiceServer).UpdateSeller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/seller.v1.SellerService/UpdateSeller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SellerServiceServer).UpdateSeller(ctx, req.(*UpdateSellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SellerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "seller.v1.SellerService",
	HandlerType: (*SellerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSeller",
			Handler:    _SellerService_CreateSeller_Handler,
		},
		{
			MethodName: "GetSellerProfile",
			Handler:    _SellerService_GetSellerProfile_Handler,
		},
		{
			MethodName: "UpdateSeller",
			Handler:    _SellerService_UpdateSeller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "seller/v1/seller.proto",
}
