// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notification/v1/notification.proto

package notificationv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageKey int32

const (
	StorageKey_STORAGE_KEY_UNSPECIFIED StorageKey = 0
	StorageKey_RESET_PASSWORD          StorageKey = 1
	StorageKey_VERIFY_EMAIL            StorageKey = 2
)

// Enum value maps for StorageKey.
var (
	StorageKey_name = map[int32]string{
		0: "STORAGE_KEY_UNSPECIFIED",
		1: "RESET_PASSWORD",
		2: "VERIFY_EMAIL",
	}
	StorageKey_value = map[string]int32{
		"STORAGE_KEY_UNSPECIFIED": 0,
		"RESET_PASSWORD":          1,
		"VERIFY_EMAIL":            2,
	}
)

func (x StorageKey) Enum() *StorageKey {
	p := new(StorageKey)
	*p = x
	return p
}

func (x StorageKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageKey) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_v1_notification_proto_enumTypes[0].Descriptor()
}

func (StorageKey) Type() protoreflect.EnumType {
	return &file_notification_v1_notification_proto_enumTypes[0]
}

func (x StorageKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageKey.Descriptor instead.
func (StorageKey) EnumDescriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

type ApproveCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           StorageKey             `protobuf:"varint,3,opt,name=key,proto3,enum=notification.v1.StorageKey" json:"key,omitempty"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveCodeRequest) Reset() {
	*x = ApproveCodeRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveCodeRequest) ProtoMessage() {}

func (x *ApproveCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveCodeRequest.ProtoReflect.Descriptor instead.
func (*ApproveCodeRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ApproveCodeRequest) GetKey() StorageKey {
	if x != nil {
		return x.Key
	}
	return StorageKey_STORAGE_KEY_UNSPECIFIED
}

func (x *ApproveCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApproveCodeRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ApproveCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetToken    string                 `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"reset_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveCodeResponse) Reset() {
	*x = ApproveCodeResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveCodeResponse) ProtoMessage() {}

func (x *ApproveCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveCodeResponse.ProtoReflect.Descriptor instead.
func (*ApproveCodeResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ApproveCodeResponse) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

type CreateNotificationRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Username            string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	NotificationMessage string                 `protobuf:"bytes,2,opt,name=notification_message,json=notificationMessage,proto3" json:"notification_message,omitempty"`
	GroupSlug           string                 `protobuf:"bytes,3,opt,name=group_slug,json=groupSlug,proto3" json:"group_slug,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateNotificationRequest) Reset() {
	*x = CreateNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRequest) ProtoMessage() {}

func (x *CreateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRequest.ProtoReflect.Descriptor instead.
func (*CreateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNotificationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateNotificationRequest) GetNotificationMessage() string {
	if x != nil {
		return x.NotificationMessage
	}
	return ""
}

func (x *CreateNotificationRequest) GetGroupSlug() string {
	if x != nil {
		return x.GroupSlug
	}
	return ""
}

type CreateNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationResponse) Reset() {
	*x = CreateNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationResponse) ProtoMessage() {}

func (x *CreateNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationResponse.ProtoReflect.Descriptor instead.
func (*CreateNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNotificationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type ListNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ToUserId       *string                `protobuf:"bytes,1,opt,name=to_user_id,json=toUserId,proto3,oneof" json:"to_user_id,omitempty"`
	ToUserUsername *string                `protobuf:"bytes,2,opt,name=to_user_username,json=toUserUsername,proto3,oneof" json:"to_user_username,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListNotificationRequest) Reset() {
	*x = ListNotificationRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationRequest) ProtoMessage() {}

func (x *ListNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListNotificationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListNotificationRequest) GetToUserId() string {
	if x != nil && x.ToUserId != nil {
		return *x.ToUserId
	}
	return ""
}

func (x *ListNotificationRequest) GetToUserUsername() string {
	if x != nil && x.ToUserUsername != nil {
		return *x.ToUserUsername
	}
	return ""
}

type ListNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationResponse) Reset() {
	*x = ListNotificationResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationResponse) ProtoMessage() {}

func (x *ListNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ListNotificationResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	GroupSlug     string                 `protobuf:"bytes,4,opt,name=group_slug,json=groupSlug,proto3" json:"group_slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Notification) GetGroupSlug() string {
	if x != nil {
		return x.GroupSlug
	}
	return ""
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\x1a'googleapis/google/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x8d\x01\n" +
	"\x12ApproveCodeRequest\x12-\n" +
	"\x03key\x18\x03 \x01(\x0e2\x1b.notification.v1.StorageKeyR\x03key\x12%\n" +
	"\x04code\x18\x01 \x01(\tB\x11\xfaB\x0er\f2\a^\\d{6}$\x98\x01\x06R\x04code\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"6\n" +
	"\x13ApproveCodeResponse\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\"\x89\x01\n" +
	"\x19CreateNotificationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x121\n" +
	"\x14notification_message\x18\x02 \x01(\tR\x13notificationMessage\x12\x1d\n" +
	"\n" +
	"group_slug\x18\x03 \x01(\tR\tgroupSlug\",\n" +
	"\x1aCreateNotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x17GetNotificationResponse\x12A\n" +
	"\fnotification\x18\x01 \x01(\v2\x1d.notification.v1.NotificationR\fnotification\"\xa7\x01\n" +
	"\x17ListNotificationRequest\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12!\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\tH\x00R\btoUserId\x88\x01\x01\x12-\n" +
	"\x10to_user_username\x18\x02 \x01(\tH\x01R\x0etoUserUsername\x88\x01\x01B\r\n" +
	"\v_to_user_idB\x13\n" +
	"\x11_to_user_username\"_\n" +
	"\x18ListNotificationResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.notification.v1.NotificationR\rnotifications\"\xae\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"group_slug\x18\x04 \x01(\tR\tgroupSlug\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*O\n" +
	"\n" +
	"StorageKey\x12\x1b\n" +
	"\x17STORAGE_KEY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eRESET_PASSWORD\x10\x01\x12\x10\n" +
	"\fVERIFY_EMAIL\x10\x022\xb0\x04\n" +
	"\x13NotificationService\x12\x8e\x01\n" +
	"\x12CreateNotification\x12*.notification.v1.CreateNotificationRequest\x1a+.notification.v1.CreateNotificationResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/notification\x12\x82\x01\n" +
	"\x0fGetNotification\x12'.notification.v1.GetNotificationRequest\x1a(.notification.v1.GetNotificationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/notification\x12\x86\x01\n" +
	"\x10ListNotification\x12(.notification.v1.ListNotificationRequest\x1a).notification.v1.ListNotificationResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/notifications\x12z\n" +
	"\vApproveCode\x12#.notification.v1.ApproveCodeRequest\x1a$.notification.v1.ApproveCodeResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/notificationsBOZMgithub.com/nhassl3/servicehub-contracts/pkg/pb/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notification_v1_notification_proto_goTypes = []any{
	(StorageKey)(0),                    // 0: notification.v1.StorageKey
	(*ApproveCodeRequest)(nil),         // 1: notification.v1.ApproveCodeRequest
	(*ApproveCodeResponse)(nil),        // 2: notification.v1.ApproveCodeResponse
	(*CreateNotificationRequest)(nil),  // 3: notification.v1.CreateNotificationRequest
	(*CreateNotificationResponse)(nil), // 4: notification.v1.CreateNotificationResponse
	(*GetNotificationRequest)(nil),     // 5: notification.v1.GetNotificationRequest
	(*GetNotificationResponse)(nil),    // 6: notification.v1.GetNotificationResponse
	(*ListNotificationRequest)(nil),    // 7: notification.v1.ListNotificationRequest
	(*ListNotificationResponse)(nil),   // 8: notification.v1.ListNotificationResponse
	(*Notification)(nil),               // 9: notification.v1.Notification
	(*timestamppb.Timestamp)(nil),      // 10: google.protobuf.Timestamp
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	0,  // 0: notification.v1.ApproveCodeRequest.key:type_name -> notification.v1.StorageKey
	9,  // 1: notification.v1.GetNotificationResponse.notification:type_name -> notification.v1.Notification
	9,  // 2: notification.v1.ListNotificationResponse.notifications:type_name -> notification.v1.Notification
	10, // 3: notification.v1.Notification.created_at:type_name -> google.protobuf.Timestamp
	3,  // 4: notification.v1.NotificationService.CreateNotification:input_type -> notification.v1.CreateNotificationRequest
	5,  // 5: notification.v1.NotificationService.GetNotification:input_type -> notification.v1.GetNotificationRequest
	7,  // 6: notification.v1.NotificationService.ListNotification:input_type -> notification.v1.ListNotificationRequest
	1,  // 7: notification.v1.NotificationService.ApproveCode:input_type -> notification.v1.ApproveCodeRequest
	4,  // 8: notification.v1.NotificationService.CreateNotification:output_type -> notification.v1.CreateNotificationResponse
	6,  // 9: notification.v1.NotificationService.GetNotification:output_type -> notification.v1.GetNotificationResponse
	8,  // 10: notification.v1.NotificationService.ListNotification:output_type -> notification.v1.ListNotificationResponse
	2,  // 11: notification.v1.NotificationService.ApproveCode:output_type -> notification.v1.ApproveCodeResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	file_notification_v1_notification_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		EnumInfos:         file_notification_v1_notification_proto_enumTypes,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
