// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cart/v1/cart.proto

package cartv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *AddItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type UpdateItemQtyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQtyRequest) Reset() {
	*x = UpdateItemQtyRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQtyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQtyRequest) ProtoMessage() {}

func (x *UpdateItemQtyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQtyRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemQtyRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemQtyRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateItemQtyRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemQtyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQtyResponse) Reset() {
	*x = UpdateItemQtyResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQtyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQtyResponse) ProtoMessage() {}

func (x *UpdateItemQtyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQtyResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemQtyResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemQtyResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_cart_v1_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{8}
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_cart_v1_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{9}
}

func (x *ClearCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_cart_v1_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{10}
}

func (x *Cart) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cart) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_cart_v1_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_cart_v1_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_cart_v1_cart_proto_rawDescGZIP(), []int{11}
}

func (x *CartItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CartItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CartItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_cart_v1_cart_proto protoreflect.FileDescriptor

const file_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x12cart/v1/cart.proto\x12\acart.v1\x1a'googleapis/google/api/annotations.proto\"\x10\n" +
	"\x0eGetCartRequest\"4\n" +
	"\x0fGetCartResponse\x12!\n" +
	"\x04cart\x18\x01 \x01(\v2\r.cart.v1.CartR\x04cart\"K\n" +
	"\x0eAddItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"4\n" +
	"\x0fAddItemResponse\x12!\n" +
	"\x04cart\x18\x01 \x01(\v2\r.cart.v1.CartR\x04cart\"2\n" +
	"\x11RemoveItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"7\n" +
	"\x12RemoveItemResponse\x12!\n" +
	"\x04cart\x18\x01 \x01(\v2\r.cart.v1.CartR\x04cart\"Q\n" +
	"\x14UpdateItemQtyRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\":\n" +
	"\x15UpdateItemQtyResponse\x12!\n" +
	"\x04cart\x18\x01 \x01(\v2\r.cart.v1.CartR\x04cart\"\x12\n" +
	"\x10ClearCartRequest\"-\n" +
	"\x11ClearCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"w\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12'\n" +
	"\x05items\x18\x03 \x03(\v2\x11.cart.v1.CartItemR\x05items\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x01R\bsubtotal\"\x95\x01\n" +
	"\bCartItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice2\x84\x04\n" +
	"\vCartService\x12R\n" +
	"\aGetCart\x12\x17.cart.v1.GetCartRequest\x1a\x18.cart.v1.GetCartResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/cart\x12[\n" +
	"\aAddItem\x12\x17.cart.v1.AddItemRequest\x1a\x18.cart.v1.AddItemResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/cart/items\x12n\n" +
	"\n" +
	"RemoveItem\x12\x1a.cart.v1.RemoveItemRequest\x1a\x1b.cart.v1.RemoveItemResponse\"'\x82\xd3\xe4\x93\x02!*\x1f/api/v1/cart/items/{product_id}\x12z\n" +
	"\rUpdateItemQty\x12\x1d.cart.v1.UpdateItemQtyRequest\x1a\x1e.cart.v1.UpdateItemQtyResponse\"*\x82\xd3\xe4\x93\x02$:\x01*2\x1f/api/v1/cart/items/{product_id}\x12X\n" +
	"\tClearCart\x12\x19.cart.v1.ClearCartRequest\x1a\x1a.cart.v1.ClearCartResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/api/v1/cartB?Z=github.com/nhassl3/servicehub-contracts/pkg/pb/cart/v1;cartv1b\x06proto3"

var (
	file_cart_v1_cart_proto_rawDescOnce sync.Once
	file_cart_v1_cart_proto_rawDescData []byte
)

func file_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)))
	})
	return file_cart_v1_cart_proto_rawDescData
}

var file_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cart_v1_cart_proto_goTypes = []any{
	(*GetCartRequest)(nil),        // 0: cart.v1.GetCartRequest
	(*GetCartResponse)(nil),       // 1: cart.v1.GetCartResponse
	(*AddItemRequest)(nil),        // 2: cart.v1.AddItemRequest
	(*AddItemResponse)(nil),       // 3: cart.v1.AddItemResponse
	(*RemoveItemRequest)(nil),     // 4: cart.v1.RemoveItemRequest
	(*RemoveItemResponse)(nil),    // 5: cart.v1.RemoveItemResponse
	(*UpdateItemQtyRequest)(nil),  // 6: cart.v1.UpdateItemQtyRequest
	(*UpdateItemQtyResponse)(nil), // 7: cart.v1.UpdateItemQtyResponse
	(*ClearCartRequest)(nil),      // 8: cart.v1.ClearCartRequest
	(*ClearCartResponse)(nil),     // 9: cart.v1.ClearCartResponse
	(*Cart)(nil),                  // 10: cart.v1.Cart
	(*CartItem)(nil),              // 11: cart.v1.CartItem
}
var file_cart_v1_cart_proto_depIdxs = []int32{
	10, // 0: cart.v1.GetCartResponse.cart:type_name -> cart.v1.Cart
	10, // 1: cart.v1.AddItemResponse.cart:type_name -> cart.v1.Cart
	10, // 2: cart.v1.RemoveItemResponse.cart:type_name -> cart.v1.Cart
	10, // 3: cart.v1.UpdateItemQtyResponse.cart:type_name -> cart.v1.Cart
	11, // 4: cart.v1.Cart.items:type_name -> cart.v1.CartItem
	0,  // 5: cart.v1.CartService.GetCart:input_type -> cart.v1.GetCartRequest
	2,  // 6: cart.v1.CartService.AddItem:input_type -> cart.v1.AddItemRequest
	4,  // 7: cart.v1.CartService.RemoveItem:input_type -> cart.v1.RemoveItemRequest
	6,  // 8: cart.v1.CartService.UpdateItemQty:input_type -> cart.v1.UpdateItemQtyRequest
	8,  // 9: cart.v1.CartService.ClearCart:input_type -> cart.v1.ClearCartRequest
	1,  // 10: cart.v1.CartService.GetCart:output_type -> cart.v1.GetCartResponse
	3,  // 11: cart.v1.CartService.AddItem:output_type -> cart.v1.AddItemResponse
	5,  // 12: cart.v1.CartService.RemoveItem:output_type -> cart.v1.RemoveItemResponse
	7,  // 13: cart.v1.CartService.UpdateItemQty:output_type -> cart.v1.UpdateItemQtyResponse
	9,  // 14: cart.v1.CartService.ClearCart:output_type -> cart.v1.ClearCartResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cart_v1_cart_proto_init() }
func file_cart_v1_cart_proto_init() {
	if File_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_v1_cart_proto_rawDesc), len(file_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_cart_v1_cart_proto = out.File
	file_cart_v1_cart_proto_goTypes = nil
	file_cart_v1_cart_proto_depIdxs = nil
}
