syntax = "proto3";

package admin.v1;

import "googleapis/google/api/annotations.proto";
import "google/protobuf/timestamp.proto";
import "moderation/v1/moderation.proto";
import "product/v1/product.proto";

option go_package = "github.com/nhassl3/servicehub-contracts/pkg/pb/admin/v1;adminv1";

service AdminService {
  rpc CreateAdmin(CreateAdminRequest) returns (CreateAdminResponse) {
    option (google.api.http) = {
      post: "/api/v1/admins"
      body: "*"
    };
  }

  rpc GetAdminProfile(GetAdminProfileRequest) returns (GetAdminProfileResponse) {
    option (google.api.http) = {
      get: "/api/v1/admins"
    };
  }

  rpc UpdateAdminProfile(UpdateAdminProfileRequest) returns (UpdateAdminProfileResponse) {
    option (google.api.http) = {
      patch: "/api/v1/admins/me"
      body: "*"
    };
  }

  rpc IncreaseTotalModerates(IncreaseAdminModeratesRequest) returns (IncreaseAdminModeratesResponse) {
    option (google.api.http) = {
      patch: "/api/v1/admins/me/increase"
      body: "*"
    };
  }

  rpc UploadAvatar(UploadAvatarRequest) returns (UploadAvatarResponse) {
    option (google.api.http) = {
      patch: "/api/v1/admins/me/uploadavatar"
      body: "*"
    };
  }

  rpc GetModeratedProducts(GetModeratedProductsRequest) returns (GetModeratedProductsResponse) {
    option (google.api.http) = {
      get: "/api/v1/admins/me/moderatedproducts"
    };
  }

  rpc GetAdminStatistics(GetAdminStatisticsRequest) returns (GetAdminStatisticsResponse) {
    option (google.api.http) = {
      get: "/api/v1/admins/me/statistics"
    };
  }
}

message GetAdminStatisticsRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2; // default last 30 days
  string granularity = 3; // "day" | "hour", default "day
}

message GetAdminStatisticsResponse {
  ProductStatusStats products = 1; // verified(active) / pending(draft) / rejected(inactive)
  repeated TopProduct top_products = 2; // by rating
  repeated CategorySales top_categories = 3;
  repeated RegistrationPoint registrations = 4; // by days/hours
  repeated ModeratePoint moderates = 5; // by days + split by admins
}

message CategorySales {
  int32 category_id = 1;
  string name = 2;
  int32 sales_count = 3; // or double total_revenue if calculate sum
}

message RegistrationPoint {
  google.protobuf.Timestamp bucket = 1; // day or hour
  int32 count = 2;
}

message ModeratePoint {
  google.protobuf.Timestamp bucket = 1;
  int32 count = 2;
  string admin_id = 3;
  string admin_name = 4;
}

message ProductStatusStats {
  int32 verified_count = 1;
  int32 pending_count = 2;
  int32 rejected_count = 3;
}

message TopProduct {
  product.v1.Product product = 1;

}

message CreateAdminRequest {
  string display_name         = 1;
  optional int32 level_rights = 2;
}

message CreateAdminResponse {
  AdminProfile admin = 1;
}

message GetAdminProfileRequest {
  optional string username = 1;
  optional string id       = 2;
}

message GetAdminProfileResponse {
  AdminProfile admin = 1;
}

message GetModeratedProductsRequest {}

message GetModeratedProductsResponse {
  repeated moderation.v1.QueueProduct products = 1;
}

message UpdateAdminProfileRequest {
  optional string display_name    = 1;
  optional string avatar_url      = 2;
  optional int32 level_rights     = 3;
  optional int32 total_moderation = 4; // if count of moderates needed to decrease
}

message UpdateAdminProfileResponse {
  AdminProfile admin = 1;
}

message IncreaseAdminModeratesRequest {
  int32 total_moderation = 1;
}

message IncreaseAdminModeratesResponse {}

message UploadAvatarRequest {
  bytes file_data     = 1;
  string content_type = 2;
}

message UploadAvatarResponse {
  AdminProfile admin = 1;
}

message AdminProfile {
  string                    id               = 1;
  string                    username         = 2;
  string                    display_name     = 3;
  int32                     level_rights     = 4;
  int32                     total_moderation = 5;
  string                    avatar_url       = 8;
  google.protobuf.Timestamp created_at       = 6;
  google.protobuf.Timestamp updated_at       = 7;
}
