// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: wishlist/v1/wishlist.proto

package wishlistv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishlistRequest) Reset() {
	*x = GetWishlistRequest{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistRequest) ProtoMessage() {}

func (x *GetWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistRequest.ProtoReflect.Descriptor instead.
func (*GetWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{0}
}

type GetWishlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*WishlistItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishlistResponse) Reset() {
	*x = GetWishlistResponse{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishlistResponse) ProtoMessage() {}

func (x *GetWishlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishlistResponse.ProtoReflect.Descriptor instead.
func (*GetWishlistResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{1}
}

func (x *GetWishlistResponse) GetItems() []*WishlistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ToggleWishlistItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWishlistItemRequest) Reset() {
	*x = ToggleWishlistItemRequest{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWishlistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWishlistItemRequest) ProtoMessage() {}

func (x *ToggleWishlistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWishlistItemRequest.ProtoReflect.Descriptor instead.
func (*ToggleWishlistItemRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{2}
}

func (x *ToggleWishlistItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ToggleWishlistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *WishlistItem          `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleWishlistItemResponse) Reset() {
	*x = ToggleWishlistItemResponse{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleWishlistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleWishlistItemResponse) ProtoMessage() {}

func (x *ToggleWishlistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleWishlistItemResponse.ProtoReflect.Descriptor instead.
func (*ToggleWishlistItemResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{3}
}

func (x *ToggleWishlistItemResponse) GetItem() *WishlistItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InWishlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InWishlistRequest) Reset() {
	*x = InWishlistRequest{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InWishlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InWishlistRequest) ProtoMessage() {}

func (x *InWishlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InWishlistRequest.ProtoReflect.Descriptor instead.
func (*InWishlistRequest) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{6}
}

func (x *InWishlistRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type InWishlistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InWishlist    bool                   `protobuf:"varint,1,opt,name=in_wishlist,json=inWishlist,proto3" json:"in_wishlist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InWishlistResponse) Reset() {
	*x = InWishlistResponse{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InWishlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InWishlistResponse) ProtoMessage() {}

func (x *InWishlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InWishlistResponse.ProtoReflect.Descriptor instead.
func (*InWishlistResponse) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{7}
}

func (x *InWishlistResponse) GetInWishlist() bool {
	if x != nil {
		return x.InWishlist
	}
	return false
}

type WishlistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Added         bool                   `protobuf:"varint,4,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishlistItem) Reset() {
	*x = WishlistItem{}
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishlistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishlistItem) ProtoMessage() {}

func (x *WishlistItem) ProtoReflect() protoreflect.Message {
	mi := &file_wishlist_v1_wishlist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishlistItem.ProtoReflect.Descriptor instead.
func (*WishlistItem) Descriptor() ([]byte, []int) {
	return file_wishlist_v1_wishlist_proto_rawDescGZIP(), []int{8}
}

func (x *WishlistItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WishlistItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *WishlistItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WishlistItem) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

var File_wishlist_v1_wishlist_proto protoreflect.FileDescriptor

const file_wishlist_v1_wishlist_proto_rawDesc = "" +
	"\n" +
	"\x1awishlist/v1/wishlist.proto\x12\vwishlist.v1\x1a'googleapis/google/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12GetWishlistRequest\"F\n" +
	"\x13GetWishlistResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.wishlist.v1.WishlistItemR\x05items\":\n" +
	"\x19ToggleWishlistItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"K\n" +
	"\x1aToggleWishlistItemResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.wishlist.v1.WishlistItemR\x04item\"2\n" +
	"\x11RemoveItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\".\n" +
	"\x12RemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11InWishlistRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"5\n" +
	"\x12InWishlistResponse\x12\x1f\n" +
	"\vin_wishlist\x18\x01 \x01(\bR\n" +
	"inWishlist\"\x8e\x01\n" +
	"\fWishlistItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05added\x18\x04 \x01(\bR\x05added2\x81\x04\n" +
	"\x0fWishlistService\x12j\n" +
	"\vGetWishlist\x12\x1f.wishlist.v1.GetWishlistRequest\x1a .wishlist.v1.GetWishlistResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/wishlist\x12\x89\x01\n" +
	"\x12ToggleWishlistItem\x12&.wishlist.v1.ToggleWishlistItemRequest\x1a'.wishlist.v1.ToggleWishlistItemResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/wishlist/toggle\x12z\n" +
	"\n" +
	"RemoveItem\x12\x1e.wishlist.v1.RemoveItemRequest\x1a\x1f.wishlist.v1.RemoveItemResponse\"+\x82\xd3\xe4\x93\x02%*#/api/v1/wishlist/items/{product_id}\x12z\n" +
	"\n" +
	"InWishlist\x12\x1e.wishlist.v1.InWishlistRequest\x1a\x1f.wishlist.v1.InWishlistResponse\"+\x82\xd3\xe4\x93\x02%\x12#/api/v1/wishlist/items/{product_id}BGZEgithub.com/nhassl3/servicehub-contracts/pkg/pb/wishlist/v1;wishlistv1b\x06proto3"

var (
	file_wishlist_v1_wishlist_proto_rawDescOnce sync.Once
	file_wishlist_v1_wishlist_proto_rawDescData []byte
)

func file_wishlist_v1_wishlist_proto_rawDescGZIP() []byte {
	file_wishlist_v1_wishlist_proto_rawDescOnce.Do(func() {
		file_wishlist_v1_wishlist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wishlist_v1_wishlist_proto_rawDesc), len(file_wishlist_v1_wishlist_proto_rawDesc)))
	})
	return file_wishlist_v1_wishlist_proto_rawDescData
}

var file_wishlist_v1_wishlist_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_wishlist_v1_wishlist_proto_goTypes = []any{
	(*GetWishlistRequest)(nil),         // 0: wishlist.v1.GetWishlistRequest
	(*GetWishlistResponse)(nil),        // 1: wishlist.v1.GetWishlistResponse
	(*ToggleWishlistItemRequest)(nil),  // 2: wishlist.v1.ToggleWishlistItemRequest
	(*ToggleWishlistItemResponse)(nil), // 3: wishlist.v1.ToggleWishlistItemResponse
	(*RemoveItemRequest)(nil),          // 4: wishlist.v1.RemoveItemRequest
	(*RemoveItemResponse)(nil),         // 5: wishlist.v1.RemoveItemResponse
	(*InWishlistRequest)(nil),          // 6: wishlist.v1.InWishlistRequest
	(*InWishlistResponse)(nil),         // 7: wishlist.v1.InWishlistResponse
	(*WishlistItem)(nil),               // 8: wishlist.v1.WishlistItem
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
}
var file_wishlist_v1_wishlist_proto_depIdxs = []int32{
	8, // 0: wishlist.v1.GetWishlistResponse.items:type_name -> wishlist.v1.WishlistItem
	8, // 1: wishlist.v1.ToggleWishlistItemResponse.item:type_name -> wishlist.v1.WishlistItem
	9, // 2: wishlist.v1.WishlistItem.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: wishlist.v1.WishlistService.GetWishlist:input_type -> wishlist.v1.GetWishlistRequest
	2, // 4: wishlist.v1.WishlistService.ToggleWishlistItem:input_type -> wishlist.v1.ToggleWishlistItemRequest
	4, // 5: wishlist.v1.WishlistService.RemoveItem:input_type -> wishlist.v1.RemoveItemRequest
	6, // 6: wishlist.v1.WishlistService.InWishlist:input_type -> wishlist.v1.InWishlistRequest
	1, // 7: wishlist.v1.WishlistService.GetWishlist:output_type -> wishlist.v1.GetWishlistResponse
	3, // 8: wishlist.v1.WishlistService.ToggleWishlistItem:output_type -> wishlist.v1.ToggleWishlistItemResponse
	5, // 9: wishlist.v1.WishlistService.RemoveItem:output_type -> wishlist.v1.RemoveItemResponse
	7, // 10: wishlist.v1.WishlistService.InWishlist:output_type -> wishlist.v1.InWishlistResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wishlist_v1_wishlist_proto_init() }
func file_wishlist_v1_wishlist_proto_init() {
	if File_wishlist_v1_wishlist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wishlist_v1_wishlist_proto_rawDesc), len(file_wishlist_v1_wishlist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wishlist_v1_wishlist_proto_goTypes,
		DependencyIndexes: file_wishlist_v1_wishlist_proto_depIdxs,
		MessageInfos:      file_wishlist_v1_wishlist_proto_msgTypes,
	}.Build()
	File_wishlist_v1_wishlist_proto = out.File
	file_wishlist_v1_wishlist_proto_goTypes = nil
	file_wishlist_v1_wishlist_proto_depIdxs = nil
}
